- hosts: webservers
  become: "yes"
  gather_facts: "yes"
  tasks:
  - name: Download package information from all configured sources
    shell: apt update
  - name: Update nodejs package
    shell: "curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -"
  - name: Install nodejs
    apt:
      name: nodejs
      state: present
  - name: Copy artifact
    synchronize:
      src: /home/ubuntu/myagent/_work/r1/a/_weight-tracker-ansbile.git/ansible/s/
      dest: /home/ubuntu/node-weight-tracker/
  - name: Install the project dependencies
    shell: >
      cd node-weight-tracker
      npm install @hapi/hapi@19 @hapi/bell@12 @hapi/boom@9 @hapi/cookie@11
      @hapi/inert@6 @hapi/joi@17 @hapi/vision@6 dotenv@8 ejs@3 postgres@1
      npm install --save-dev nodemon@2
  - name: Copy .env
    synchronize:
      src: /home/ubuntu/myagent/_work/r1/a/.env
      dest: /home/ubuntu/node-weight-tracker
  - name: Install pm2
    shell: npm install pm2 -g
  - name: Npm initialization
    shell: npm init -y
    args:
      chdir: /home/ubuntu/node-weight-tracker/
  - name: Running NPM install
    shell: npm install
    register: npm_finished
    args:
      chdir: /home/ubuntu/node-weight-tracker/
  - name: Init DB
    shell: npm run initdb
    args:
      chdir: '/home/ubuntu/node-weight-tracker/'
  - name: Start app
    shell: pm2 start npm -- run dev pm2 save && pm2 startup
    args:
      chdir: '/home/ubuntu/node-weight-tracker/'

  - name: Save process autorun
    shell: pm2 save
