- hosts: servers
  become: "yes"
  gather_facts: "yes"
  tasks:
  - name: "Update packages"
    shell: apt update

  - name: "Install Docker"
    shell: apt install docker.io -y

  - name: "Change mode to docker.sock"
    shell: chmod 666 /var/run/docker.sock

  - name: "Login to ACR"
    shell: docker login -u {{ acrLogin }} -p {{ acrPass }} {{ registry }}

  - name: "Remove old container"
    shell: docker rm -f bootcampapp || true

  - name: "Docker run"
    shell: docker run -d --restart=always --name bootcampapp -p 8080:8080 {{ registry }}/bootcampapp:{{ tag }}

  - name: ".env template"
    template:
      src: './.env'
      dest: '/home/ubuntu/bootcampapp'
      owner: 'ubuntu'
      mode: u=r,g=r,o=r

  - name: "Copy .env to Docker container"
    shell: docker cp /home/ubuntu/.env {{ registry }}/bootcampapp:{{ tag }}/.env

  - name: "Restart container"
    shell: docker restart bootcampapp 

